### ISSUE TITLE
rows and columns

### ISSUE THREAD

**Issue by klocey** [LennonLab/StarvationTraits#11]
In the data, what are the rows and what are columns? @meglarsen @mmuscarella @jaytlennon

**Comment by jaytlennon** [comment]
Just how resources are "printed" onto plates

**Comment by klocey** [comment]
LOL, durr. It was a long day ;)

**Comment by mmuscarella** [comment]
I added a notes folder with the datasheet for the EcoPlate. The sheet describes what each well contains.

**Comment by jaytlennon** [comment]
@mmuscarella @nwisnoski: I just saw this. I didn't transfer over the EcoPlate pdf, since wasn't sure if it was for Rachel's or SSRP's stuff. 

I actually spent some time tonight making an `eco.plate.info.txt.` file that is on the SSRP repo. I transcribed info over from BIOLOG pdf info page. 

Also, I took a stab at a higher order classification scheme for each of the substrates. It's probably not perfect, but it's a start. Feel free to take a peak and modify as you see fit. 

cc: @klocey @meglarsen @wrshoemaker
